apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: learns.app.learn.com
spec:
  group: app.learn.com
  names:
    kind: Learn
    listKind: LearnList
    plural: learns
    singular: learn
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
