// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/jianzhangbjz/learn-operator/pkg/apis/app/v1.Learn":       schema_pkg_apis_app_v1_Learn(ref),
		"github.com/jianzhangbjz/learn-operator/pkg/apis/app/v1.LearnSpec":   schema_pkg_apis_app_v1_LearnSpec(ref),
		"github.com/jianzhangbjz/learn-operator/pkg/apis/app/v1.LearnStatus": schema_pkg_apis_app_v1_LearnStatus(ref),
	}
}

func schema_pkg_apis_app_v1_Learn(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Learn is the Schema for the learns API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/jianzhangbjz/learn-operator/pkg/apis/app/v1.LearnSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/jianzhangbjz/learn-operator/pkg/apis/app/v1.LearnStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/jianzhangbjz/learn-operator/pkg/apis/app/v1.LearnSpec", "github.com/jianzhangbjz/learn-operator/pkg/apis/app/v1.LearnStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_app_v1_LearnSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "LearnSpec defines the desired state of Learn",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_app_v1_LearnStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "LearnStatus defines the observed state of Learn",
				Type:        []string{"object"},
			},
		},
	}
}
